### ISSUE TITLE
Help with SSO plugin.

### ISSUE THREAD

**Issue by endyjasmi** [iceman91176/camunda-sso-tomcat#2]
Good day, I have followed the readme up till the SSO plugin session. Currently I have a camunda login page which is authenticated against the Keycloak.

So, I have downloaded the `keycloak.json` and placed it in `$CAMUNDA_HOME/conf`. Right after this, whenever I access `/camunda` it just showed page with 404 error.

It seems that tomcat is not booting camunda after I enabled SSO plugin.
Here is the log line (not sure if it is related)
```
28-Nov-2019 13:18:50.302 WARN [main] org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.keycloakInit No adapter configuration. Keycloak is unconfigured and will deny all requests.
28-Nov-2019 13:18:50.304 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/camunda/webapps/docs] has finished in [10,349] ms
28-Nov-2019 13:18:50.304 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/camunda/webapps/camunda]
28-Nov-2019 13:19:01.036 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
28-Nov-2019 13:19:01.434 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
28-Nov-2019 13:19:01.434 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/camunda] startup failed due to previous errors
28-Nov-2019 13:19:01.453 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/camunda/webapps/camunda] has finished in [11,149] ms
28-Nov-2019 13:19:01.454 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/camunda/webapps/camunda-invoice] 
```

Any help would be greatly appreciated and thanks in advance the help given.

Do let me know if you need any extra information.

**Side note**
I am running this by building and mounting the jar into the official camunda docker image.

**Comment by iceman91176** [comment]
Hey,
the first line of the logfiles states

> org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.keycloakInit No adapter configuration. Keycloak is unconfigured and will deny all requests.

which seems weird, because we are not using the KeycloakAuthenticatorValve any more.  Could you check your tomcat-configuration for "context.xml" files that reference the KeycloakAuthenticatorValve ?

But the main problem is here 

> SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file

Could you please post the contaiber log, which should be located in the tomcat-logs dir (localhost.xxx.log)

Thank you

**Comment by yenyih** [comment]
Hi, i got the same problem. The problem is because it unable to find the class KeycloakSSOAuthenticationProvider, the class path for camunda-web.xml and engine-rest-web.xml is different with the classpath after packaged (jar). In order to fix this, I changed the 

`<param-value>de.witcom.bpm.sso.KeycloakSSOAuthenticationProvider</param-value>`

to

`<param-value>org.camunda.community.auth.keycloak.sso.KeycloakSSOAuthenticationProvider</param-value>`

and for engine-rest-web.xml:

`<filter-class>de.witcom.bpm.filter.KeycloakAuthenticationFilter</filter-class>`

to

`<filter-class>org.camunda.community.auth.keycloak.filter.KeycloakAuthenticationFilter</filter-class>`

**Comment by iceman91176** [comment]
Oops, look like some leftovers ;-) I am going to correct that in the docs
