### ISSUE TITLE
Help with logout

### ISSUE THREAD

**Issue by yenyih** [iceman91176/camunda-sso-tomcat#3]
Hi, I have successful setup camunda auth keycloak sso with your sso plugin. But the Logout is not working. When I logout, it did route me to login page, but keycloak session didn't logout. If I manually load the page to any webapps, it will directly logged me in. Could you provide me a path? How can I handle logout?

**Comment by iceman91176** [comment]
This is because you are not logged out from keycloak's point of view. Logout from Keycloak works like this https://www.keycloak.org/docs/latest/securing_apps/#logout. Since nobody performs the Logout-Request/Redirect, your session is still valid.

The functionality you are looking for is related to the Web-UI. 
Try something like this

* https://forum.camunda.org/t/custom-logout-event/6508
